[project]
name = "uv-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "gunicorn>=23.0.0",
    "psutil>=7.0.0",
    "sqlalchemy-bigquery>=1.12.1",
    "uvicorn>=0.34.0",
]
